data:
  input: data/dataset_v3.csv

split:
  test_size: 0.2
  random_state: 42

models:
  linear_regression:

  random_forest_regressor:
    n_estimators: 100
    max_depth: 5
    random_state: 42

  gradient_boosting_regressor:
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 5
    random_state: 42